version: '3.8'

services:
  # 1. Config Server (Must start first)
  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:/config-repo
    volumes:
      - "./config-repo:/config-repo"
    networks:
      - realestate-net
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. Discovery Service (Waits for Config)
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8080"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888/
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - realestate-net

  # 3. Gateway Service
  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8080/eureka/
    depends_on:
      config-server:
        condition: service_healthy
      discovery-service:
        condition: service_started
    networks:
      - realestate-net

  # 4. Product Service
  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8080/eureka/
    depends_on:
      config-server:
        condition: service_healthy
      discovery-service:
        condition: service_started
    networks:
      - realestate-net

  # 5. Order Service
  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8080/eureka/
    depends_on:
      config-server:
        condition: service_healthy
      discovery-service:
        condition: service_started
    networks:
      - realestate-net

  # 6. Front API
  front-api:
    build: ./front-api
    container_name: front-api
    ports:
      - "8083:8083"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8080/eureka/
    depends_on:
      config-server:
        condition: service_healthy
      discovery-service:
        condition: service_started
      product-service:
        condition: service_started
      order-service:
        condition: service_started
    networks:
      - realestate-net

networks:
  realestate-net:
    driver: bridge
