version: '3.8'

services:
  # 1. Config Server (Must start first)
  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      - GIT_REPO_URI=https://github.com/kaizokuni/real-estate-config-repo.git
    networks:
      - realestate-net
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. Discovery Service (Waits for Config)
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888/
    depends_on:
      - config-server
    networks:
      - realestate-net

  # 3. Gateway Service
  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
    networks:
      - realestate-net

  # 4. Estate Service
  estate-service:
    build: ./estate-service
    container_name: estate-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
    networks:
      - realestate-net

  # 5. Client Service
  client-service:
    build: ./client-service
    container_name: client-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
    networks:
      - realestate-net

  # 6. Front API
  front-api:
    build: ./front-api
    container_name: front-api
    ports:
      - "8083:8083"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
      - estate-service
      - client-service
    networks:
      - realestate-net

networks:
  realestate-net:
    driver: bridge
